version: 2

project_name: terraform-credentials-amiasea

builds:
  - id: tfcred
    main: ./cmd/terraform-credentials-amiasea/tfcred
    binary: tfcred
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
    goos:
      - windows
    goarch:
      - amd64

  - id: terraform-credentials-amiasea
    main: ./cmd/terraform-credentials-amiasea
    binary: terraform-credentials-amiasea
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
    goos:
      - windows
    goarch:
      - amd64

archives:
  - id: default

    formats: 
      - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README*
      - LICENSE*
      - contexts.json

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: amiasea
    name: terraform-credentials-amiasea
